#ifndef VSLC_H
#define VSLC_H
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>

/* Definition of the tree node type, and functions for handling the parse tree */
#include "tree.h"

/* Function for generating machine code, in generator.c */
void generate_program ( void );

/* The main driver function of the parser generated by bison */
int yyparse ();

/* A "hidden" cleanup function in flex */
int yylex_destroy ();

#endif // VSLC_H
